apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: machinesets.cluster.k8s.io
spec:
  group: cluster.k8s.io
  names:
    kind: MachineSet
    plural: machinesets
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            minReadySeconds:
              format: int32
              type: integer
            replicas:
              format: int32
              type: integer
            selector:
              type: object
            template:
              properties:
                metadata:
                  type: object
                spec:
                  properties:
                    configSource:
                      type: object
                    metadata:
                      type: object
                    providerSpec:
                      properties:
                        value:
                          type: object
                        valueFrom:
                          type: object
                      type: object
                    taints:
                      items:
                        type: object
                      type: array
                    versions:
                      properties:
                        controlPlane:
                          type: string
                        kubelet:
                          type: string
                      required:
                      - kubelet
                      type: object
                  required:
                  - providerSpec
                  type: object
              type: object
          required:
          - selector
          type: object
        status:
          properties:
            availableReplicas:
              format: int32
              type: integer
            errorMessage:
              type: string
            errorReason:
              type: string
            fullyLabeledReplicas:
              format: int32
              type: integer
            observedGeneration:
              format: int64
              type: integer
            readyReplicas:
              format: int32
              type: integer
            replicas:
              format: int32
              type: integer
          required:
          - replicas
          type: object
  version: v1alpha1
  additionalPrinterColumns:
  - JSONPath: .spec.replicas
    description: Desired Replicas
    name: Desired
    type: integer
  - JSONPath: .status.replicas
    description: Current Replicas
    name: Current
    type: integer
  - JSONPath: .status.readyReplicas
    description: Ready Replicas
    name: Ready
    type: integer
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
