apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler-controllers
  namespace: kube-system
  labels:
    api: cluster-autoscaler
    k8s-app: controller
spec:
  selector:
    matchLabels:
      api: cluster-autoscaler
      k8s-app: controller
  replicas: 1
  template:
    metadata:
      labels:
        api: cluster-autoscaler
        k8s-app: controller
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        key: node.alpha.kubernetes.io/notReady
        operator: Exists
      - effect: NoExecute
        key: node.alpha.kubernetes.io/unreachable
        operator: Exists
      serviceAccountName: cluster-autoscaler
      containers:
      - name: cluster-autoscaler
        image: gofed/cluster-autoscaler:cluster-api-0.1.0
        command:
          - /usr/bin/cluster-autoscaler
        args:
          - --logtostderr=true
          - --cloud-provider=clusterapi
          - --namespace=kube-system
          - --expendable-pods-priority-cutoff=-10
          - --max-nodes-total=24
          - --scale-down-enabled=true
          - --scale-down-delay-after-add=10s
          - --scale-down-delay-after-delete=10s
          - --scale-down-delay-after-failure=10s
          - --scale-down-unneeded-time=23s
          - --leader-elect=false
          - --v=3
