apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterapi-manager-controllers
  namespace: default
  labels:
    api: clusterapi
    k8s-app: controller
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  selector:
    matchLabels:
      api: clusterapi
      k8s-app: controller
  replicas: 1
  template:
    metadata:
      labels:
        api: clusterapi
        k8s-app: controller
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        key: node.alpha.kubernetes.io/notReady
        operator: Exists
      - effect: NoExecute
        key: node.alpha.kubernetes.io/unreachable
        operator: Exists
      containers:
      - name: controller-manager
        image: gofed/kubemark-machine-controllers:1e737b9
        command:
        - "./manager"
        args:
          - --logtostderr=true
          - --v=3
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      - name: machine-controller
        image: gofed/kubemark-machine-controllers:1e737b9
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        command:
          - /machine-controller-manager
        args:
          - --logtostderr=true
          - --v=3
      - name: nodelink-controller
        image: quay.io/coreos/machine-api-operator:origin-v4.0-2019-01-31-041134
        command:
          - /nodelink-controller
        args:
          - --logtostderr=true
          - --v=3
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      - name: cluster-autoscaler
        image: docker.io/openshift/origin-cluster-autoscaler:v4.0
        command:
          - /bin/cluster-autoscaler
        args:
          - --logtostderr
          - --scan-interval=10s
          - --cloud-provider=cluster-api
          - --scale-down-delay-after-add=10s
          - --scale-down-delay-after-delete=10s
          - --scale-down-delay-after-failure=10s
          - --scale-down-unneeded-time=10s
          - --leader-elect=false
          - -v=4
        resources:
          requests:
            cpu: 500m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 200Mi
      - name: unready-nodes-gb
        image: gofed/kubemark-machine-controllers:1e737b9
        command:
          - /bin/entrypoint.sh
        volumeMounts:
        - name: deleteunreadynodes
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
      volumes:
      - name: deleteunreadynodes
        configMap:
          defaultMode: 0700
          name: deleteunreadynodes
