---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterapi-manager-controllers
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: nodelink-controller
        image: registry.svc.ci.openshift.org/openshift/origin-v4.0-2019-02-13-200735@sha256:65a62e5b4d6cd90c238bd580b4c53888f706f3597ac8f626a9dc11bf16853132 # NODELINK_CONTROLLER_IMAGE
