---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: kubemark-scale-group-2b
  namespace: kube-system
spec:
  replicas: 0
  selector:
    matchLabels:
      sigs.k8s.io/cluster-api-machineset: kubemark-scale-group-2b
  template:
    metadata:
      labels:
        sigs.k8s.io/cluster-api-machineset: kubemark-scale-group-2b
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          apiVersion: kubemarkproviderconfig.k8s.io/v1alpha1
          kind: KubemarkMachineProviderConfig
      versions:
        kubelet: 1.10.1
        controlPlane: 1.10.1
