---
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineSet
metadata:
  name: kubemark-actuator-testing-machine
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      sigs.k8s.io/cluster-api-machineset: test-kubemark
  template:
    metadata:
      labels:
        sigs.k8s.io/cluster-api-machineset: test-kubemark
    spec:
      providerSpec:
        value:
          apiVersion: kubemarkproviderconfig.k8s.io/v1alpha1
          kind: KubemarkMachineProviderConfig
          # turnUnhealthyAfter: true
          unhealthyDuration: 5s
          healthyDuration: 5s
          turnUnhealthyPeriodically: true
      versions:
        kubelet: 1.10.1
        controlPlane: 1.10.1
