---
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  name: kubemark-actuator-testing-machine
  namespace: default
  labels:
    machine.openshift.io/cluster-api-cluster: kubemark
spec:
  providerSpec:
    value:
      apiVersion: kubemarkproviderconfig.k8s.io/v1alpha1
      kind: KubemarkMachineProviderConfig
      # turnUnhealthyAfter: true
      unhealthyDuration: 5s
      healthyDuration: 5s
      turnUnhealthyPeriodically: true
      image: docker.io/gofed/kubemark:v1.14.3-beta.0-2
      numCores: 2
      memoryCapacity: 10737418240
  versions:
    kubelet: 1.10.1
    controlPlane: 1.10.1
